---

- name: Install x509_certificate__packages
  apt:
    name: "{{ x509_certificate__packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Install x509_certificate__additional_packages
  apt:
    name: "{{ x509_certificate__additional_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
